#!/bin/bash

#Calculate Average of Columns
numRows=$(awk 'END {print NR}' $1) #Get number of rows
numCols=$(awk 'END {print NF}' $1) #Get number of columns
counter=0
total=0
for((i=1; i<=$numCols; i++))
do
	a+=($(awk '{print $var}' var="$i" $1)) #Go through each column and place it into the a array. Pass $i from bash to awk
done
for ((i=0; i<$numCols; i++)) #iterate through each column
do
	for((j=0; j<$numRows; j++)) #and iterate through each value in each column
	do
		total=$((total + ${a[counter]})) #add them up to the total
		tempArr+=(${a[counter]}) #create temporary array to sort for median
		((counter++)) #increase the counter to move to the next value
	done
	halves=$((numRows / 2)) #calculate the halves, used for rounding and median
	tempArr=($(for each in ${tempArr[@]}; do echo $each; done | sort)) #Sort the temporary array
	if [ $((numRows%2)) -eq 0 ]; #If the number of rows is even
		then
			index=$((halves)) #Go to the higher middle
			median=${tempArr[index]}
		else
			index=$halves #go to the middle
			median=${tempArr[index]}
		fi
	average=$((total + halves)) #make the numerator the total + halves
	average=$((average / numRows)) #divide the numerator by the number of items
	total=0 #reset total for the next one
	unset tempArr #reset the tempArr for the next one
	averageArr+=($average) #Add the averages to an array we'll print out later
	medianArr+=($median) #Add the medians to an array we'll print out later
done
#Print out the values
echo "Averages:"
for((i=0;i<$numRows;i++))
do
	printf "${averageArr[i]}	"
done
printf "\n"
echo "Medians:"
for((i=0;i<$numRows;i++))
do
	printf "${medianArr[i]}	"
done
printf "\n"